apiVersion: apps/v1
kind: Deployment
metadata:
        name: new-deployment
        namespace: default
        labels:
                app: naga

spec:
        replicas: 2
        selector:
                matchLabels:
                        app: naga

        template:
                metadata:
                        name: newapp
                        labels:
                                app: naga

                spec:
                        containers:
                        -       name: naga-container
                                image: nagamlak/virtual-folio:1.1
                                ports:
                                - containerPort: 80
                                
                              
--- 
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: default
spec:
  selector:
    app: naga
    tier: frontend

  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
                                
                                
                                
